import fs from 'node:fs';
import path from 'node:path';

const createdBy = 'Nhóm dự án PKA Portal';
const createdDate = '26/07/2026';
const commonAuthException = 'Phiên đăng nhập thiếu, hết hạn hoặc người dùng không đúng vai trò: hệ thống từ chối yêu cầu và yêu cầu đăng nhập lại.';

const U = (id, title, main, secondary, description, trigger, pre, post, flow, alt, exceptions, priority, rules, assumptions, ui) => ({
  id, title, main, secondary, description, trigger, pre, post, flow, alt, exceptions, priority, rules, assumptions, ui
});

const useCases = [
  U('UC1.1','Quản lý khoa','Phòng Đào tạo','Không có',
    'Quản lý danh mục khoa làm dữ liệu nền cho ngành đào tạo và hồ sơ giảng viên.',
    'Cán bộ mở mục Cấu hình đào tạo – Khoa.',
    'Đã đăng nhập với vai trò pdt.',
    'Khoa được tạo/cập nhật/xóa hợp lệ; dữ liệu giữ nguyên nếu thất bại.',
    ['Hệ thống tải danh sách khoa theo tên.','Cán bộ nhập mã và tên khoa.','Hệ thống kiểm tra dữ liệu bắt buộc và mã duy nhất.','Hệ thống lưu khoa và tải lại danh sách.'],
    ['Cán bộ đổi tên khoa.','Cán bộ xóa khoa chưa có ngành hoặc giảng viên.','Cán bộ hủy thao tác.'],
    [commonAuthException,'Thiếu mã/tên hoặc trùng mã: từ chối lưu.','Khoa đang có ngành/giảng viên: từ chối xóa.'],
    'Cao',
    ['Mã khoa là duy nhất.','Không xóa khoa còn dữ liệu phụ thuộc.','Chỉ vai trò pdt được quản lý.'],
    ['Mã khoa do nhà trường quy định.','Danh sách khoa đủ nhỏ để chưa cần phân trang.'],'UI-01'),

  U('UC1.2','Quản lý ngành đào tạo','Phòng Đào tạo','Không có',
    'Quản lý ngành trực thuộc khoa; ngành được dùng cho hồ sơ sinh viên và phân loại môn học.',
    'Cán bộ mở mục Cấu hình đào tạo – Ngành.',
    'Đã đăng nhập vai trò pdt và có ít nhất một khoa.',
    'Ngành và liên kết khoa được lưu hợp lệ.',
    ['Hệ thống tải khoa và ngành.','Cán bộ nhập mã, tên ngành và chọn khoa.','Hệ thống kiểm tra khoa tồn tại và mã ngành duy nhất.','Hệ thống lưu ngành và hiển thị tên khoa.'],
    ['Đổi tên ngành.','Chuyển ngành sang khoa khác.','Xóa ngành chưa có sinh viên/môn học.'],
    [commonAuthException,'Khoa không tồn tại hoặc thiếu dữ liệu: từ chối lưu.','Ngành có sinh viên/môn học: từ chối xóa.'],
    'Cao',
    ['Mỗi ngành thuộc một khoa.','Mã ngành là duy nhất.','Không xóa ngành còn dữ liệu phụ thuộc.'],
    ['Khoa được tạo trước ngành.','Chưa quản lý lịch sử chuyển ngành.'],'UI-01'),

  U('UC2.1','Quản lý tài khoản và hồ sơ sinh viên','Quản trị viên','Phòng Đào tạo cung cấp ngành',
    'Tạo và quản lý đồng thời tài khoản đăng nhập cùng hồ sơ học vụ của sinh viên.',
    'Quản trị viên chọn quản lý người dùng – Sinh viên.',
    'Đã đăng nhập vai trò admin; ngành đã tồn tại.',
    'User và Student được tạo/cập nhật đồng bộ trong transaction.',
    ['Admin nhập username, mật khẩu, MSV, họ tên, email, lớp, ngành và ngày nhập học.','Hệ thống kiểm tra dữ liệu trùng và ngành tồn tại.','Hệ thống băm mật khẩu.','Hệ thống tạo User và Student trong một transaction.','Hệ thống ghi Audit Log và hiển thị hồ sơ.'],
    ['Admin sửa họ tên, giới tính, ngày sinh, email, lớp hoặc ngành.','Admin lọc danh sách theo vai trò student.'],
    [commonAuthException,'Username/MSV/email trùng hoặc ngành không tồn tại: rollback.','Thiếu trường bắt buộc: từ chối tạo.'],
    'Cao',
    ['Một User gắn tối đa một Student.','Mật khẩu tối thiểu 8 ký tự và phải băm.','Tạo tài khoản/hồ sơ là thao tác nguyên tử.'],
    ['Mỗi sinh viên thuộc một ngành và một lớp sinh hoạt tại một thời điểm.'],'UI-02'),

  U('UC2.2','Quản lý tài khoản và hồ sơ giảng viên','Quản trị viên','Phòng Đào tạo cung cấp khoa',
    'Tạo và quản lý tài khoản cùng hồ sơ chuyên môn của giảng viên.',
    'Admin chọn quản lý người dùng – Giảng viên.',
    'Đã đăng nhập vai trò admin; khoa đã tồn tại.',
    'User và Lecturer được lưu đồng bộ.',
    ['Admin nhập username, mật khẩu, MGV, họ tên, email, khoa, chức vụ và môn chính.','Hệ thống kiểm tra trùng và khoa tồn tại.','Hệ thống băm mật khẩu.','Hệ thống tạo User và Lecturer trong transaction.','Hệ thống ghi nhật ký.'],
    ['Sửa hồ sơ giảng viên.','Lọc danh sách theo lecturer.'],
    [commonAuthException,'Username/MGV/email trùng hoặc khoa không tồn tại: rollback.'],
    'Cao',
    ['Một User gắn tối đa một Lecturer.','Giảng viên phải thuộc một khoa.','Mật khẩu không lưu dạng rõ.'],
    ['Phân công lớp được thực hiện sau khi hồ sơ giảng viên tồn tại.'],'UI-02'),

  U('UC2.3','Quản lý tài khoản cán bộ','Quản trị viên','Không có',
    'Tạo và quản lý tài khoản cho Phòng Đào tạo và quản trị viên.',
    'Admin chọn thêm tài khoản cán bộ.',
    'Đã đăng nhập vai trò admin.',
    'Tài khoản pdt/admin được tạo với quyền tương ứng.',
    ['Admin nhập username, mật khẩu và vai trò pdt hoặc admin.','Hệ thống kiểm tra username duy nhất và độ dài mật khẩu.','Hệ thống băm mật khẩu và tạo User.','Hệ thống ghi Audit Log.'],
    ['Admin thay đổi trạng thái hoặc đặt lại mật khẩu.'],
    [commonAuthException,'Username trùng hoặc vai trò không hợp lệ: từ chối tạo.'],
    'Cao',
    ['Vai trò chỉ thuộc tập admin, pdt, lecturer, student.','Tài khoản mới mặc định active và isFirstLogin.'],
    ['Tài khoản cán bộ không cần hồ sơ Student/Lecturer.'],'UI-02'),

  U('UC2.4','Quản lý vòng đời tài khoản','Quản trị viên','Người dùng bị tác động',
    'Khóa, mở khóa, đặt lại mật khẩu hoặc xóa tài khoản và dữ liệu liên quan.',
    'Admin chọn thao tác trên một tài khoản.',
    'Tài khoản đích tồn tại; admin đã xác thực.',
    'Trạng thái/mật khẩu được cập nhật hoặc tài khoản được xóa an toàn.',
    ['Admin chọn tài khoản.','Hệ thống hiển thị hồ sơ và trạng thái.','Admin chọn khóa, mở khóa, đặt lại mật khẩu hoặc xóa.','Hệ thống kiểm tra yêu cầu.','Hệ thống cập nhật/xóa trong transaction và ghi Audit Log.'],
    ['Admin hủy xác nhận.','Admin chỉ sửa hồ sơ mà không đổi trạng thái.'],
    [commonAuthException,'Tài khoản không tồn tại.','Xóa thất bại ở một bảng: rollback toàn bộ.'],
    'Cao',
    ['Tài khoản locked không được đăng nhập.','Xóa User xử lý profile, token và thông báo theo quan hệ.'],
    ['Admin chịu trách nhiệm xác nhận đúng đối tượng trước khi xóa.'],'UI-02'),

  U('UC3.1','Quản lý học kỳ','Phòng Đào tạo','Không có',
    'Quản lý mã, tên, thời gian, trạng thái và học kỳ hiện hành.',
    'Cán bộ mở cấu hình học kỳ.',
    'Đã đăng nhập vai trò pdt.',
    'Học kỳ được lưu; chỉ một kỳ được đánh dấu hiện hành.',
    ['Cán bộ nhập mã, tên, ngày bắt đầu/kết thúc và trạng thái.','Hệ thống kiểm tra thời gian.','Nếu chọn hiện hành, hệ thống bỏ cờ hiện hành ở kỳ khác.','Hệ thống lưu trong transaction.'],
    ['Sửa học kỳ.','Đặt một học kỳ khác làm hiện hành.','Xóa học kỳ chưa sử dụng.'],
    [commonAuthException,'Ngày kết thúc không sau ngày bắt đầu.','Không xóa học kỳ hiện hành hoặc đã có lớp.'],
    'Cao',
    ['Chỉ một AcademicTerm có isCurrent=true.','Trạng thái thuộc planned/active/closed.'],
    ['Mã học kỳ theo dạng HK1-YYYY hoặc quy ước tương đương.'],'UI-03'),

  U('UC3.2','Quản lý đợt đăng ký','Phòng Đào tạo','Sinh viên sử dụng thời gian cấu hình',
    'Thiết lập các khoảng mở/đóng cổng đăng ký gắn với học kỳ.',
    'Cán bộ chọn quản lý đợt đăng ký.',
    'Học kỳ đã tồn tại; người dùng là pdt.',
    'RegistrationPeriod được lưu và trạng thái cổng được xác định đúng.',
    ['Cán bộ chọn học kỳ, nhập tên, thời gian mở/đóng và trạng thái bật.','Hệ thống kiểm tra kỳ tồn tại và thời gian hợp lệ.','Hệ thống lưu đợt.','Frontend nhận trạng thái cổng hiện tại/đợt tiếp theo.'],
    ['Sửa thời gian.','Bật/tắt đợt.','Xóa đợt.'],
    [commonAuthException,'Học kỳ không tồn tại.','Thời gian đóng không sau thời gian mở.'],
    'Cao',
    ['Cổng mở khi isEnabled=true và thời gian máy chủ nằm trong khoảng.','Đợt phải thuộc một học kỳ.'],
    ['Đồng hồ máy chủ là nguồn thời gian chuẩn.'],'UI-03'),

  U('UC4.1','Quản lý môn học','Phòng Đào tạo','Không có',
    'Tạo và tra cứu môn học với mã, tên, tín chỉ, ngành và học kỳ lộ trình.',
    'Cán bộ mở danh mục môn học.',
    'Ngành cần gán đã tồn tại; người dùng là pdt.',
    'Course mới được lưu và xuất hiện trong danh sách.',
    ['Hệ thống tải danh sách môn có phân trang.','Cán bộ nhập mã, tên, tín chỉ, ngành và term.','Hệ thống kiểm tra dữ liệu và mã duy nhất.','Hệ thống tạo môn.'],
    ['Tạo môn dùng chung với majorId rỗng.','Tra cứu các trang danh sách.'],
    [commonAuthException,'Trùng mã hoặc dữ liệu không hợp lệ: từ chối tạo.'],
    'Cao',
    ['Mã môn là duy nhất.','Tín chỉ là số nguyên dương.','majorId rỗng biểu thị môn dùng chung.'],
    ['API hiện tập trung xem/tạo môn, chưa có cập nhật/xóa môn.'],'UI-04'),

  U('UC4.2','Thiết lập môn tiên quyết và lộ trình','Phòng Đào tạo','Sinh viên chịu điều kiện',
    'Gắn môn học với học kỳ đề xuất và môn tiên quyết để kiểm soát đăng ký.',
    'Cán bộ nhập thông tin chương trình khi tạo môn.',
    'Môn tiên quyết (nếu có) đã tồn tại.',
    'Quan hệ prerequisite và term được lưu.',
    ['Cán bộ chọn ngành và học kỳ đề xuất.','Cán bộ chọn môn tiên quyết.','Hệ thống kiểm tra môn tiên quyết tồn tại và khác môn hiện tại.','Hệ thống lưu cấu hình.'],
    ['Không chọn tiên quyết đối với môn cơ sở.','Để majorId rỗng cho môn dùng chung.'],
    [commonAuthException,'Môn tự tham chiếu hoặc môn tiên quyết không tồn tại.'],
    'Cao',
    ['Môn không được tiên quyết chính nó.','Sinh viên phải có điểm khóa khác F ở môn tiên quyết.'],
    ['Chỉ mô hình một môn tiên quyết trực tiếp cho mỗi Course.'],'UI-04'),

  U('UC5.1','Mở lớp học phần','Phòng Đào tạo','Giảng viên',
    'Mở lớp từ môn học, gán giảng viên, phòng, lịch và sức chứa trong một học kỳ.',
    'Cán bộ chọn tạo lớp học phần.',
    'Course, Lecturer và AcademicTerm đã tồn tại.',
    'Class trạng thái active được tạo nếu không xung đột.',
    ['Cán bộ nhập mã lớp, môn, giảng viên, phòng, loại phòng, sức chứa và lịch.','Hệ thống xác định học kỳ.','Hệ thống kiểm tra giao nhau của phòng.','Hệ thống kiểm tra giao nhau lịch giảng viên.','Hệ thống tạo lớp active.'],
    ['Xem danh sách lớp có phân trang.'],
    [commonAuthException,'Trùng phòng hoặc trùng giảng viên trong khoảng tiết.','Mã lớp hoặc dữ liệu tham chiếu không hợp lệ.'],
    'Cao',
    ['Khoảng giao nhau khi start1<end2 và start2<end1.','Một phòng/giảng viên không phục vụ hai lớp giao giờ.'],
    ['Lịch học dùng thứ, ca, tiết bắt đầu và số tiết.'],'UI-05'),

  U('UC5.2','Hủy lớp thiếu sĩ số','Phòng Đào tạo','Sinh viên bị ảnh hưởng',
    'Hủy lớp có dưới 15 sinh viên và đồng bộ đăng ký, học phí.',
    'Cán bộ chọn hủy một lớp.',
    'Lớp tồn tại, active; người dùng là pdt.',
    'Lớp canceled; đăng ký bị xóa; học phí được tính lại.',
    ['Hệ thống khóa transaction và tải lớp.','Đếm sinh viên enrolled.','Nếu dưới 15, đổi lớp thành canceled.','Xóa đăng ký liên quan.','Tính lại học phí từng sinh viên.','Ghi Audit Log và commit.'],
    ['Cán bộ hủy xác nhận trước khi gửi.'],
    [commonAuthException,'Lớp không tồn tại/đã hủy.','Sĩ số từ 15 trở lên: từ chối.','Lỗi giữa quy trình: rollback.'],
    'Cao',
    ['Chỉ hủy theo luồng này khi enrolled<15.','Mọi thay đổi phải nguyên tử.'],
    ['Quyết định hủy do Phòng Đào tạo thực hiện.'],'UI-05'),

  U('UC6.1','Đăng nhập và quản lý phiên','Người dùng','Không có',
    'Xác thực bằng username/email/MSV/MGV, cấp token, làm mới phiên và đăng xuất.',
    'Người dùng gửi biểu mẫu đăng nhập.',
    'Tài khoản tồn tại và chưa bị khóa.',
    'Phiên hợp lệ được cấp hoặc toàn bộ token được thu hồi khi đăng xuất.',
    ['Người dùng nhập định danh và mật khẩu.','Hệ thống tìm User, kiểm tra status và bcrypt.','Hệ thống cấp access/refresh token.','Frontend tải vai trò và hồ sơ.','Khi token hết hạn, hệ thống xoay refresh token.'],
    ['Đăng xuất một phiên.','Đăng xuất tất cả thiết bị.','Tự nâng cấp mật khẩu cũ sau đăng nhập đúng.'],
    ['Sai thông tin hoặc locked: từ chối.','Refresh token hết hạn/bị thu hồi.'],
    'Cao',
    ['Refresh token chỉ dùng một lần rồi xoay.','tokenVersion phải khớp User.'],
    ['Thiết bị lưu token theo cơ chế frontend hiện tại.'],'UI-06'),

  U('UC6.2','Đổi và khôi phục mật khẩu','Người dùng','Dịch vụ Email/SMTP',
    'Đổi mật khẩu khi biết mật khẩu cũ hoặc đặt lại bằng OTP sáu chữ số.',
    'Người dùng chọn đổi/quên mật khẩu.',
    'Tài khoản active; có email khi dùng OTP.',
    'Mật khẩu mới được băm; OTP xóa; phiên cũ bị thu hồi khi reset.',
    ['Người dùng yêu cầu OTP bằng định danh.','Hệ thống tạo và băm OTP, hạn 5 phút.','SMTP gửi OTP tới email che mờ.','Người dùng nhập OTP và mật khẩu mới.','Hệ thống xác thực, lưu mật khẩu và thu hồi phiên.'],
    ['Đổi mật khẩu bằng mật khẩu hiện tại.','OTP demo chỉ khi môi trường phát triển cho phép.'],
    ['OTP sai/hết hạn; tài khoản locked; mật khẩu mới dưới 8 ký tự.'],
    'Cao',
    ['OTP dùng một lần và có hạn 5 phút.','Mật khẩu tối thiểu 8 ký tự, băm bcrypt.'],
    ['SMTP được cấu hình trong production.'],'UI-06'),

  U('UC6.3','Xem và cập nhật hồ sơ cá nhân','Người dùng','Không có',
    'Hiển thị tài khoản, hồ sơ vai trò, học kỳ hiện hành; sinh viên được cập nhật email.',
    'Người dùng mở hồ sơ.',
    'Đã xác thực.',
    'Hồ sơ/ngữ cảnh được hiển thị; email mới được lưu nếu hợp lệ.',
    ['Hệ thống đọc User.','Theo vai trò, tải Student kèm Major/Department hoặc Lecturer kèm Department.','Tính tiến độ học kỳ sinh viên.','Hiển thị hồ sơ.','Nếu sinh viên sửa email, hệ thống lưu và ghi log.'],
    ['Chỉ xem hồ sơ.','Tải riêng ngữ cảnh kỳ và đợt đăng ký.'],
    [commonAuthException,'Không tìm thấy profile tương ứng.'],
    'Trung bình',
    ['Người dùng không tự sửa các trường học vụ khác.','Học kỳ lấy từ AcademicTerm hiện hành.'],
    ['Quản trị viên xử lý các sửa đổi hồ sơ nâng cao.'],'UI-06'),

  U('UC7.1','Tra cứu và đăng ký học phần','Sinh viên','Phòng Đào tạo cấu hình dữ liệu',
    'Tra cứu lớp phù hợp và đăng ký sau khi kiểm tra toàn bộ điều kiện học vụ.',
    'Sinh viên chọn Đăng ký tại một lớp.',
    'Đã đăng nhập student; cổng mở; lớp active.',
    'Registration enrolled hoặc waitlist được tạo; học phí/log được cập nhật.',
    ['Hệ thống lọc lớp theo ngành/lộ trình.','Sinh viên chọn lớp.','Hệ thống khóa lớp trong transaction.','Kiểm tra trùng đăng ký, ngành, lộ trình, tiên quyết, lịch và tín chỉ.','Kiểm tra capacity.','Tạo enrolled hoặc waitlist, tính học phí, ghi log và commit.'],
    ['Nếu lớp đầy, gán queueOrder.','Xác định retake/improve từ điểm cũ.'],
    ['Cổng đóng; lớp hủy; thiếu tiên quyết; trùng lịch; vượt 24/12 tín chỉ; sinh viên đã bị buộc thôi học.'],
    'Rất cao',
    ['Student thường tối đa 24 TC, cảnh báo tối đa 12 TC, buộc thôi học không được đăng ký.','Danh sách ưu tiên theo thứ tự: học lại, nâng điểm, học mới theo chương trình.','Chỉ điểm khóa khác F thỏa tiên quyết.','Hàng chờ FIFO.'],
    ['Dữ liệu lịch lớp chính xác.'],'UI-07'),

  U('UC7.2','Hủy đăng ký và xử lý hàng chờ','Sinh viên','Sinh viên đầu hàng chờ',
    'Hủy lớp trong thời gian cho phép và tự động đôn người đầu hàng chờ.',
    'Sinh viên chọn Hủy tại đăng ký.',
    'Cổng mở; đăng ký thuộc sinh viên.',
    'Đăng ký bị xóa; hàng chờ/học phí được đồng bộ.',
    ['Hệ thống mở transaction và tìm đăng ký.','Kiểm tra cổng.','Xóa đăng ký.','Nếu bản ghi enrolled, tìm queueOrder nhỏ nhất.','Đôn người chờ, tính học phí và gửi thông báo.','Đánh lại queueOrder, tính học phí người hủy, ghi log, commit.'],
    ['Hủy bản ghi waitlist chỉ cần đánh lại thứ tự.','Không có người chờ thì chỉ cập nhật học phí người hủy.'],
    ['Không tìm thấy đăng ký; cổng đóng; lỗi transaction.'],
    'Rất cao',
    ['FIFO theo queueOrder tăng dần.','Tất cả bước phải commit/rollback cùng nhau.'],
    ['Sinh viên được phép rút môn trong toàn bộ đợt đăng ký.'],'UI-07'),

  U('UC7.3','Xem đăng ký và thời khóa biểu','Sinh viên','Không có',
    'Hiển thị danh sách đăng ký và lưới lịch học chính thức.',
    'Sinh viên mở Môn đã đăng ký hoặc Thời khóa biểu.',
    'Đã xác thực student.',
    'Danh sách/lịch của học kỳ hiện hành được hiển thị.',
    ['Hệ thống tìm Student từ token.','Tải Registration kèm Class, Course, Lecturer.','Lọc enrolled và lớp active cho thời khóa biểu.','Trả môn, phòng, thứ, ca và tiết.'],
    ['Danh sách đăng ký có thể hiển thị cả waitlist.'],
    [commonAuthException,'Không tìm thấy hồ sơ sinh viên.'],
    'Cao',
    ['Lịch chính thức chỉ gồm enrolled.','Lớp canceled không hiển thị.'],
    ['Mỗi lớp có một lịch cố định trong mô hình hiện tại.'],'UI-07'),

  U('UC8.1','Nhập và import điểm','Giảng viên','Sinh viên trong lớp',
    'Nhập từng sinh viên hoặc import Excel; tự tính tổng hệ 10, chữ và hệ 4.',
    'Giảng viên mở bảng điểm lớp.',
    'Giảng viên phụ trách lớp; Grade tồn tại; điểm chưa khóa.',
    'Điểm hợp lệ được lưu và Audit Log được tạo.',
    ['Hệ thống kiểm tra quyền lớp.','Giảng viên nhập 3 đầu điểm hoặc tải xlsx.','Hệ thống kiểm tra sinh viên và miền 0–10.','Tính tổng 10%-30%-60% và quy đổi.','Lưu điểm và log.'],
    ['Import nhiều dòng trong một transaction.','Sửa điểm chưa khóa.'],
    ['Không thuộc lớp; thiếu Grade; điểm ngoài miền; file sai cấu trúc; điểm đã khóa.'],
    'Rất cao',
    ['Mỗi đầu điểm 0–10.','Import có một dòng lỗi phải rollback toàn bộ.'],
    ['File import theo mẫu hệ thống xuất.'],'UI-08'),

  U('UC8.2','Khóa, công bố và xuất bảng điểm lớp','Giảng viên','Sinh viên',
    'Chốt bảng điểm khi đủ dữ liệu, thông báo cho sinh viên và cho phép xuất Excel.',
    'Giảng viên chọn Khóa bảng điểm.',
    'Phụ trách lớp; mọi sinh viên có đủ 3 đầu điểm.',
    'Tất cả Grade của lớp isLocked=true; sinh viên nhận thông báo.',
    ['Hệ thống kiểm tra quyền.','Đếm Grade thiếu thành phần.','Nếu bằng 0, khóa toàn lớp.','Ghi Audit Log.','Tạo thông báo cho từng sinh viên.','Cho phép xuất workbook Excel.'],
    ['Giảng viên chỉ xuất bảng điểm mà chưa khóa.'],
    ['Còn điểm thiếu: từ chối khóa và nêu số lượng.','Không thuộc lớp: từ chối.'],
    'Rất cao',
    ['Điểm khóa không sửa qua API thường.','Sinh viên chỉ xem điểm khóa.'],
    ['Phúc khảo là luồng duy nhất cập nhật điểm khóa.'],'UI-08'),

  U('UC9.1','Xem kết quả, GPA, CPA và tiến độ','Sinh viên','Không có',
    'Tổng hợp điểm chính thức, GPA theo kỳ, CPA và tín chỉ hoàn thành.',
    'Sinh viên mở Kết quả học tập.',
    'Có hồ sơ student và điểm đã khóa.',
    'Bảng điểm và chỉ số học tập được hiển thị.',
    ['Hệ thống tải Grade isLocked kèm Course.','Nhóm điểm theo học kỳ.','Tính GPA theo tín chỉ.','Chọn điểm hệ 4 cao nhất mỗi môn để tính CPA.','Đếm tín chỉ khác F và tính phần trăm trên 120 TC.'],
    ['Nếu chưa có điểm, hiển thị trạng thái trống và chỉ số 0.'],
    [commonAuthException,'Dữ liệu Course thiếu làm một dòng không thể tính tín chỉ.'],
    'Cao',
    ['GPA/CPA có trọng số tín chỉ.','CPA lấy kết quả cao nhất mỗi môn.'],
    ['Tổng tín chỉ tốt nghiệp demo là 120.'],'UI-09'),

  U('UC9.2','Yêu cầu và xử lý phúc khảo','Sinh viên','Giảng viên',
    'Sinh viên yêu cầu xem xét điểm khóa; giảng viên phụ trách chấm lại và cập nhật kết quả.',
    'Sinh viên chọn Phúc khảo tại một điểm.',
    'Điểm thuộc sinh viên, đã khóa và chưa có yêu cầu.',
    'reEvalStatus chuyển requested rồi completed; kết quả/log/thông báo được cập nhật.',
    ['Sinh viên nhập lý do.','Hệ thống lưu requested và log.','Giảng viên xem yêu cầu của lớp mình.','Giảng viên nhập lại 3 đầu điểm.','Hệ thống tính lại, lưu trước/sau và completed.','Gửi thông báo sinh viên.'],
    ['Giảng viên giữ nguyên điểm sau khi xem xét nhưng vẫn hoàn thành yêu cầu.'],
    ['Điểm chưa khóa; yêu cầu trùng; giảng viên không phụ trách; điểm mới không hợp lệ.'],
    'Cao',
    ['Mỗi Grade chỉ có một yêu cầu đang xử lý.','Chỉ giảng viên lớp được giải quyết.'],
    ['Quy trình chưa có bước duyệt bổ sung của Phòng Đào tạo.'],'UI-09'),

  U('UC9.3','Quản lý cảnh báo học vụ','Phòng Đào tạo','Sinh viên',
    'Quét GPA/CPA và cập nhật trạng thái cảnh báo của sinh viên.',
    'Cán bộ mở Cảnh báo học vụ.',
    'Có điểm khóa; người dùng là pdt.',
    'Danh sách cảnh báo hiển thị; status sinh viên được cập nhật khi duyệt.',
    ['Hệ thống tải Student và Grade khóa theo đúng học kỳ của lớp.','Tính GPA kỳ và CPA.','Lọc GPA<1.0 hoặc CPA<1.5, đồng thời giữ sinh viên đang có trạng thái học vụ để xét khôi phục.','Lần cảnh báo đầu đề xuất warning_1; nếu tiếp diễn đề xuất warning_2.','Cán bộ duyệt chuyển trạng thái theo thứ tự và hệ thống ghi log.'],
    ['Xuất danh sách cảnh báo Excel.','Phân trang danh sách.'],
    [commonAuthException,'Không tìm thấy sinh viên khi cập nhật.'],
    'Cao',
    ['Ngưỡng GPA<1.0 hoặc CPA<1.5.','warning_1/2 làm giới hạn đăng ký còn 12 TC.','dismissed không được đăng ký học phần.','Không được bỏ qua trình tự active → warning_1 → warning_2 → dismissed.'],
    ['Cán bộ quyết định mức cảnh báo sau khi xem gợi ý.'],'UI-09'),

  U('UC10.1','Quản lý hóa đơn và miễn giảm','Phòng Đào tạo','Sinh viên',
    'Tính hóa đơn theo tín chỉ enrolled, thống kê và điều chỉnh miễn giảm.',
    'Đăng ký thay đổi hoặc cán bộ mở Quản lý học phí.',
    'Có Student, Registration và Course.',
    'Payment được tạo/cập nhật với amount, discountRate, finalAmount và deadline.',
    ['Hệ thống tổng hợp tín chỉ enrolled của lớp active.','Tính amount=tín chỉ×đơn giá.','Tạo/cập nhật Payment.','Cán bộ có thể nhập tỷ lệ và lý do giảm.','Hệ thống tính finalAmount và ghi log.'],
    ['Miễn 100% tự chuyển paid.','Lọc paid/unpaid, tìm MSV/tên/lớp và xem thống kê.'],
    ['Tỷ lệ ngoài 0–1; không tìm thấy hóa đơn.'],
    'Rất cao',
    ['Waitlist không tính học phí.','FinalAmount=round(amount×(1-rate)).'],
    ['Đơn giá demo COST_PER_CREDIT=1000; deadline mặc định sau 2 tháng.'],'UI-10'),

  U('UC10.2','Thanh toán và đối soát trực tuyến','Sinh viên','SePay/Ngân hàng',
    'Thanh toán qua QR và xác nhận bằng webhook hoặc kiểm tra API SePay.',
    'Sinh viên mở QR hoặc SePay gửi giao dịch.',
    'Hóa đơn unpaid thuộc sinh viên; tích hợp được cấu hình.',
    'Payment paid, lưu transactionId/paidAt; giao diện nhận sự kiện.',
    ['Hệ thống hiển thị QR với PKABILL<id>.','Ngân hàng ghi nhận giao dịch.','Webhook/API cung cấp giao dịch.','Hệ thống xác thực nguồn, chiều tiền, mã hóa đơn và số tiền.','Cập nhật paid và phát payment_confirmed.'],
    ['Kiểm tra chủ động 20 giao dịch gần nhất.','Mô phỏng thanh toán trong development.'],
    ['Sai secret; giao dịch out; thiếu mã; số tiền thiếu; hóa đơn đã paid.'],
    'Rất cao',
    ['Mã hóa đơn phải khớp chính xác.','Không xử lý trùng giao dịch.'],
    ['SePay cung cấp API/webhook đúng định dạng.'],'UI-10'),

  U('UC10.3','Xác nhận thanh toán thủ công','Phòng Đào tạo','Sinh viên',
    'Gạch nợ tiền mặt/chuyển khoản trực tiếp khi không dùng đối soát tự động.',
    'Cán bộ chọn Xác nhận thủ công tại hóa đơn.',
    'Hóa đơn tồn tại và unpaid.',
    'Hóa đơn paid, có mã PDT-MANUAL, phương thức, ghi chú và thời gian.',
    ['Cán bộ chọn hóa đơn.','Nhập phương thức và ghi chú.','Hệ thống kiểm tra unpaid.','Tạo mã giao dịch và cập nhật paid.','Ghi Audit Log.','Phát payment_confirmed tới sinh viên.'],
    ['Dùng phương thức mặc định nếu để trống.'],
    [commonAuthException,'Hóa đơn không tồn tại hoặc đã paid.'],
    'Cao',
    ['Chỉ pdt được gạch nợ.','Mỗi hóa đơn chỉ xác nhận một lần.'],
    ['Cán bộ đã kiểm tra chứng từ ngoài hệ thống.'],'UI-10'),

  U('UC10.4','Xuất báo cáo học phí và biên lai','Sinh viên','Phòng Đào tạo',
    'Xuất danh sách học phí Excel và biên lai HTML có thể in.',
    'Người dùng chọn chức năng xuất.',
    'Đã xác thực đúng vai trò; có dữ liệu hóa đơn.',
    'Tệp Excel hoặc HTML được tải về.',
    ['Hệ thống kiểm tra quyền.','Lấy Payment, Student và chi tiết lớp.','Tạo workbook hoặc HTML.','Đặt tiêu đề, cột, tổng tiền và thông tin giao dịch.','Trả tệp tải xuống.'],
    ['Sinh viên xuất biên lai cá nhân.','PDT xuất toàn bộ báo cáo kỳ.'],
    [commonAuthException,'Không có hóa đơn hoặc lỗi tạo tệp.'],
    'Trung bình',
    ['Sinh viên chỉ xuất dữ liệu của mình.','Báo cáo PDT dùng học kỳ hiện hành.'],
    ['Người dùng có ứng dụng mở xlsx hoặc trình duyệt để in HTML.'],'UI-10'),

  U('UC11.1','Quản lý thông báo cá nhân','Người dùng','Hệ thống thời gian thực',
    'Lưu, đẩy và quản lý trạng thái đọc của thông báo nghiệp vụ.',
    'Phát sinh sự kiện đăng ký, điểm, phúc khảo hoặc thanh toán.',
    'Người nhận có User; socket đã xác thực nếu trực tuyến.',
    'Notification được lưu; người dùng nhận và có thể đánh dấu đã đọc.',
    ['Nghiệp vụ gọi createNotification.','Hệ thống lưu type, title, message, data.','Socket.IO phát tới user_<id>.','Người dùng tải danh sách phân trang.','Người dùng đánh dấu một hoặc tất cả đã đọc.'],
    ['Lọc unread=true.','Đếm số chưa đọc.'],
    [commonAuthException,'Không tìm thấy thông báo thuộc người dùng.','Socket offline: dữ liệu vẫn lưu để đọc sau.'],
    'Cao',
    ['Người dùng chỉ đọc/cập nhật thông báo của mình.','readAt được lưu khi đánh dấu đọc.'],
    ['Kết nối thời gian thực là bổ sung, không thay thế lưu CSDL.'],'UI-11'),

  U('UC12.1','Tra cứu nhật ký hệ thống','Quản trị viên','Phòng Đào tạo',
    'Tra cứu các thao tác nhạy cảm phục vụ kiểm tra và truy vết.',
    'Admin/PDT mở Nhật ký hệ thống.',
    'Đã xác thực vai trò admin hoặc pdt.',
    'Danh sách AuditLog mới nhất được hiển thị theo trang.',
    ['Hệ thống nhận bộ phân trang.','Kiểm tra quyền.','Truy vấn AuditLog theo createdAt giảm dần.','Hiển thị username, action, details, IP và thời gian.'],
    ['Chuyển trang danh sách.'],
    [commonAuthException,'Lỗi truy vấn nhật ký.'],
    'Cao',
    ['Nghiệp vụ nhạy cảm phải ghi action và thời gian.','User bị xóa có thể để userId null nhưng giữ thông tin log.'],
    ['Nhật ký hiện chưa có bộ lọc nâng cao theo ngày/action.'],'UI-12'),

  U('UC12.2','Xem thống kê và xuất báo cáo đào tạo','Phòng Đào tạo','Giảng viên và sinh viên cung cấp dữ liệu',
    'Tổng hợp số lượng, cảnh báo, điểm và học phí; xuất các báo cáo Excel.',
    'Cán bộ mở Dashboard hoặc chọn Xuất báo cáo.',
    'Dữ liệu nghiệp vụ đã tồn tại; người dùng là pdt.',
    'Chỉ số hoặc tệp báo cáo được hiển thị/tải xuống.',
    ['Hệ thống đếm sinh viên, giảng viên, môn và lớp.','Tổng hợp paid/unpaid, phải thu/đã thu.','Tính danh sách cảnh báo khi yêu cầu.','Tạo workbook tương ứng.','Trả số liệu hoặc tệp.'],
    ['Giảng viên xuất bảng điểm lớp.','Sinh viên xuất bảng điểm cá nhân.'],
    [commonAuthException,'Không có dữ liệu hoặc lỗi tạo workbook.'],
    'Trung bình',
    ['Báo cáo theo phạm vi vai trò.','Số liệu học phí theo học kỳ hiện hành.'],
    ['Excel là định dạng trao đổi chính của phiên bản hiện tại.'],'UI-12')
];

const esc = (value) => String(value ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>');
const ol = (items) => `<ol>${items.map((x) => `<li>${esc(x)}</li>`).join('')}</ol>`;
const sectionNumber = (index) => `1.6.${index + 1}`;
let md = `# 1.6 ĐẶC TẢ CÁC USE-CASE\n\n`;
md += `Tài liệu đặc tả **${useCases.length} Use-case mức 2** của PKA Portal, được sắp xếp theo thứ tự hình thành và phụ thuộc dữ liệu. Mỗi Use-case sử dụng đúng cấu trúc bảng thống nhất và tham chiếu tới giao diện minh họa ở Phụ lục A.\n\n`;

useCases.forEach((u, index) => {
  md += `## ${sectionNumber(index)} ${u.id}. ${u.title}\n\n`;
  md += `| Trường đặc tả | Nội dung |\n|---|---|\n`;
  md += `| **Số và tên UC** | **${u.id}. ${esc(u.title)}** |\n`;
  md += `| **Người tạo UC** | ${createdBy} |\n`;
  md += `| **Ngày tạo UC** | ${createdDate} |\n`;
  md += `| **Mô tả** | ${esc(u.description)} |\n`;
  md += `| **Tác nhân chính** | ${esc(u.main)} |\n`;
  md += `| **Tác nhân phụ (nếu có)** | ${esc(u.secondary)} |\n`;
  md += `| **Sự kiện kích hoạt** | ${esc(u.trigger)} |\n`;
  md += `| **Tiền điều kiện** | ${esc(u.pre)} |\n`;
  md += `| **Hậu điều kiện** | ${esc(u.post)} |\n`;
  md += `| **Luồng thông thường** | ${ol(u.flow)} |\n`;
  md += `| **Luồng thay thế** | ${ol(u.alt)} |\n`;
  md += `| **Các ngoại lệ** | ${ol(u.exceptions)} |\n`;
  md += `| **Độ ưu tiên** | ${esc(u.priority)} |\n`;
  md += `| **Các quy tắc nghiệp vụ** | ${ol(u.rules)} |\n`;
  md += `| **Các giả thuyết** | ${ol(u.assumptions)} |\n`;
  md += `| **Giao diện minh họa** | **${u.ui}** – xem Phụ lục A. Giao diện chứa dữ liệu minh họa và các thao tác tương ứng với luồng UC. |\n\n`;
});

md += `# PHỤ LỤC A. DANH MỤC GIAO DIỆN MINH HỌA\n\n`;
md += `| Mã giao diện | Màn hình | Use-case áp dụng | Dữ liệu minh họa chính |\n|---|---|---|---|\n`;
const uiRows = [
  ['UI-01','Cấu hình khoa và ngành','UC1.1, UC1.2','Khoa CNTT, Kinh tế, Ngoại ngữ; ngành CNTT, QTKD, NNA'],
  ['UI-02','Quản lý tài khoản và hồ sơ','UC2.1–UC2.4','SV 24100001 Nguyễn Minh Anh; GV GV001 Trần Văn Nam; trạng thái active/locked'],
  ['UI-03','Học kỳ và đợt đăng ký','UC3.1, UC3.2','HK1-2026; đợt chính 01/08–15/08/2026'],
  ['UI-04','Môn học và chương trình','UC4.1, UC4.2','INT101, Cơ sở lập trình, 3 tín chỉ; tiên quyết MAT101'],
  ['UI-05','Lớp học phần','UC5.1, UC5.2','INT101_L01; GV001; A101; Thứ 2; ca sáng; 12/40 sinh viên'],
  ['UI-06','Đăng nhập, mật khẩu và hồ sơ','UC6.1–UC6.3','Tài khoản 24100001; email n***@st.phenikaa-uni.edu.vn'],
  ['UI-07','Đăng ký và thời khóa biểu','UC7.1–UC7.3','INT101_L01 enrolled; WEB201_L02 waitlist số 2; tổng 18 tín chỉ'],
  ['UI-08','Bảng điểm giảng viên','UC8.1, UC8.2','Chuyên cần 9; giữa kỳ 8; cuối kỳ 8.5; tổng 8.4; điểm chữ B'],
  ['UI-09','Kết quả, phúc khảo và cảnh báo','UC9.1–UC9.3','GPA 3.12; CPA 3.05; 72/120 tín chỉ; phúc khảo requested'],
  ['UI-10','Học phí và thanh toán','UC10.1–UC10.4','Hóa đơn #24; PKABILL24; miễn giảm 10%; trạng thái unpaid'],
  ['UI-11','Thông báo','UC11.1','Công bố điểm, được vào lớp từ hàng chờ, thanh toán thành công'],
  ['UI-12','Dashboard, báo cáo và Audit Log','UC12.1, UC12.2','NHAP_DIEM, HUY_LOP, GACH_NO; thống kê 500 SV, 42 GV']
];
uiRows.forEach((r) => { md += `| ${r.map(esc).join(' | ')} |\n`; });
md += `\nBộ mock-up tương tác đi kèm tài liệu sử dụng cùng các mã UI-01 đến UI-12. Các màn hình được thiết kế theo dữ liệu và luồng xử lý hiện có trong frontend PKA Portal.\n`;

const outPath = path.resolve('PKA_Portal_Use_Case_Specifications.md');
fs.writeFileSync(outPath, md, 'utf8');
console.log(`Wrote ${outPath} with ${useCases.length} use cases.`);
